#:import MapView kivy_garden.mapview.MapView
#:import GpsBlinker gpsblinker.GpsBlinker
 
<MrtLrtMapView>:
    zoom: 15
    double_tap_zoom: True
    on_zoom:
        self.zoom = 15 if self.zoom < 15 else self.zoom # set minimum zoom = 15
    on_lat:
        self.start_getting_mrtlrt_in_fov() # on getting latitude
    on_lon:
        self.start_getting_mrtlrt_in_fov() # on getting longitude
    GpsBlinker:
        lat: root.lat
        lon: root.lon
        id: mrtlrtblinker