#:import MapView kivy_garden.mapview.MapView
#:import GpsBlinker gpsblinker.GpsBlinker
 
<IncidentsMapView>:
    zoom: 13
    double_tap_zoom: True
    on_zoom:
        self.zoom = 13 if self.zoom < 13 else self.zoom # set minimum zoom = 13
    on_lat:
        self.start_getting_incidents_in_fov() # on getting latitude
    on_lon:
        self.start_getting_incidents_in_fov() # on getting longitude
    GpsBlinker:
        lat: root.lat
        lon: root.lon
        id: incidentsblinker