#:import MapView kivy_garden.mapview.MapView
#:import GpsBlinker gpsblinker.GpsBlinker
 
<CarParkMapView>:
    zoom: 16
    double_tap_zoom: True
    on_zoom:
        self.zoom = 16 if self.zoom < 16 else self.zoom # set minimum zoom = 16
    on_lat:
        self.start_getting_carpark_in_fov() # on getting latitude
    on_lon:
        self.start_getting_carpark_in_fov() # on getting longitude
    GpsBlinker:
        lat: root.lat
        lon: root.lon
        id: carparkblinker